// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRy9EGZK--pJR9lr16U1kpyqHaF5STVo',
    appId: '1:1005463114212:web:aefd20c8083350ca1577f1',
    messagingSenderId: '1005463114212',
    projectId: 'flutter-template-acafc',
    authDomain: 'flutter-template-acafc.firebaseapp.com',
    storageBucket: 'flutter-template-acafc.appspot.com',
    measurementId: 'G-4HT1F5S2R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5kmHQdZoYKFX8uSZ_H2SdzSQyP_Q-pg0',
    appId: '1:1005463114212:android:2920cd8cd464f2d51577f1',
    messagingSenderId: '1005463114212',
    projectId: 'flutter-template-acafc',
    storageBucket: 'flutter-template-acafc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpdtvfE3Li01D-zshL_SKnFV4QJA7Zs7o',
    appId: '1:1005463114212:ios:075e97c02eb2a4bd1577f1',
    messagingSenderId: '1005463114212',
    projectId: 'flutter-template-acafc',
    storageBucket: 'flutter-template-acafc.appspot.com',
    iosBundleId: 'com.rkwdk.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpdtvfE3Li01D-zshL_SKnFV4QJA7Zs7o',
    appId: '1:1005463114212:ios:5283f2afac4b621c1577f1',
    messagingSenderId: '1005463114212',
    projectId: 'flutter-template-acafc',
    storageBucket: 'flutter-template-acafc.appspot.com',
    iosBundleId: 'com.example.nutriMeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNRy9EGZK--pJR9lr16U1kpyqHaF5STVo',
    appId: '1:1005463114212:web:79cdbaec97ff153c1577f1',
    messagingSenderId: '1005463114212',
    projectId: 'flutter-template-acafc',
    authDomain: 'flutter-template-acafc.firebaseapp.com',
    storageBucket: 'flutter-template-acafc.appspot.com',
    measurementId: 'G-D87C591QXG',
  );

}